Fix: do not cause exceptions when index is not yet ready
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
        at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:842)
        at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:791)
        at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:775)
        at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:249)
        at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:237)
        at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:76)
        at com.intellij.psi.stubs.StubIndex.process(StubIndex.java:95)
        at com.intellij.psi.stubs.StubIndexImpl.get(StubIndexImpl.java:226)
        at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:144)
        at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
        at com.jetbrains.php.PhpIndexImpl.getClassesByNameInScope(PhpIndexImpl.java:217)
        at com.jetbrains.php.PhpIndexImpl.getClassesByName(PhpIndexImpl.java:211)
        at com.jetbrains.php.PhpIndexImpl.getClassesByFQN(PhpIndexImpl.java:472)
        at idea.plugins.prado.PradoControlUtil.classForFieldReference(PradoControlUtil.java:23)
        at idea.plugins.prado.completion.ControlTypeProvider.getType(ControlTypeProvider.java:35)